export const mockMovies = [
  {
    id: 1,
    title: 'Interstellar',
    rating: 8.7,
    overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity has a future.',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg',
    trailerKey: 'zSWdZVtXT7E',
  },
  {
    id: 2,
    title: 'Blade Runner 2049',
    rating: 8.0,
    overview: 'A young blade runner discovers a long-buried secret that leads him to track down former blade runner Rick Deckard.',
    genres: ['Sci-Fi', 'Mystery', 'Thriller'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    trailerKey: 'gCcx85zbxz4',
  },
  {
    id: 3,
    title: 'The Dark Knight',
    rating: 9.0,
    overview: 'Batman raises the stakes in his war on crime while facing the Joker.',
    genres: ['Action', 'Crime', 'Drama'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    trailerKey: 'EXeTwQWrcwY',
  },
  {
    id: 4,
    title: 'Dune: Part Two',
    rating: 8.6,
    overview: 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators.',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    trailerKey: 'Way9Dexny3w',
  },
  {
    id: 5,
    title: 'Inception',
    rating: 8.8,
    overview: 'A thief who steals corporate secrets through dream-sharing technology is tasked with planting an idea.',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    trailerKey: 'YoHD9XEInc0',
  },
  {
    id: 6,
    title: 'Oppenheimer',
    rating: 8.4,
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    genres: ['Drama', 'History'],
    language: 'en',
    posterPath: 'https://image.tmdb.org/t/p/w500/ptpr0kGAckfQkJeJIt8st5dglvd.jpg',
    trailerKey: 'uYPbbksJxIg',
  },
  {
    id: 7,
    title: 'RRR',
    rating: 7.9,
    overview: 'A fearless warrior and a revolutionary leader unite in pre-independent India.',
    genres: ['Action', 'Drama'],
    language: 'te',
    posterPath: 'https://image.tmdb.org/t/p/w500/wE6bfgT2R1hjd0D6M5Qf4M7cLJ2.jpg',
    trailerKey: 'f_vbAtFSEc0',
  },
  {
    id: 8,
    title: '3 Idiots',
    rating: 8.3,
    overview: 'Two friends search for their long-lost companion while reliving engineering college days.',
    genres: ['Comedy', 'Drama'],
    language: 'hi',
    posterPath: 'https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8Tew.jpg',
    trailerKey: 'K0eDlFX9GMc',
  },
  {
    id: 9,
    title: 'Jailer',
    rating: 7.2,
    overview: 'A retired jailer seeks revenge after his son goes missing.',
    genres: ['Action', 'Thriller'],
    language: 'ta',
    posterPath: 'https://image.tmdb.org/t/p/w500/eM3Oz9y7x9dcj8N8sV6A6RzGQ4k.jpg',
    trailerKey: 'Y5BeWdODPqo',
  },
]

export const mockAiRecommendations = [
  { id: 101, title: 'The Martian', rating: 8.0, posterPath: 'https://image.tmdb.org/t/p/w500/5aGhaIHYuQbqlHWvWYqMCnj40y2.jpg' },
  { id: 102, title: 'Gravity', rating: 7.7, posterPath: 'https://image.tmdb.org/t/p/w500/kZ2nZw8D681aphje8NJi8EfbL1U.jpg' },
  { id: 103, title: 'Arrival', rating: 8.0, posterPath: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg' },
]
